version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: messenger-db
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    image: java-messenger:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_PASSWORD: ${PG_PASSWORD}

volumes:
  pgdata: