name: Selenium E2E Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
        options: >-
          --shm-size=2g

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install frontend dependencies
      working-directory: ./messenger-frontend
      run: npm ci

    - name: Start frontend
      working-directory: ./messenger-frontend
      run: npm run start&
      env:
        CI: true

    - name: Build backend
      run: ./mvnw package -DskipTests

    - name: Start application stack
      run: docker compose up -d

    - name: Wait for services to be ready
      run: sleep 15

    - name: Set up Python virtual environment
      working-directory: ./selenium-e2e
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Selenium E2E tests
      working-directory: ./selenium-e2e
      run: bash run.sh

    - name: Upload test reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: selenium-test-reports
        path: target/surefire-reports/

